### DISCUSSION TITLE
Can I force input key names remain as such, rather than become values of `key` and `value`? If so, how?

### DISCUSSION THREAD

**Discussion by beedell-roke** [cloudbase/powershell-yaml#151] [Q&A] [answered]
#### **Examples**

```PS1
Get-ItemProperty -LiteralPath 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion' | Format-List
```

The aforementioned command outputs the undermentioned data:

```YAML
SystemRoot                : C:\WINDOWS
BuildBranch               : ge_release
BuildLab                  : 26100.ge_release.240331-1435
BuildLabEx                : 26100.1.amd64fre.ge_release.240331-1435
CompositionEditionID      : Enterprise
CurrentBuild              : 26100
CurrentBuildNumber        : 26100
CurrentMajorVersionNumber : 10
CurrentMinorVersionNumber : 0
CurrentType               : Multiprocessor Free
CurrentVersion            : 6.3
DisplayVersion            : 24H2
EditionID                 : Professional
InstallationType          : Client
InstallDate               : 1719779588
LCUVer                    : 10.0.26100.2152
ProductName               : Windows 10 Pro
```

This is valid YAML (albeit not intentionally so). What matters for this discussion is that in the first line (and all) the key name is `SystemRoot`, and the value, `C:\WINDOWS`.

However, if I put it through `ConvertTo-YAML`, as undermentioned:

```PS1
$YAML = @'
SystemRoot                : C:\WINDOWS
BuildBranch               : ge_release
BuildLab                  : 26100.ge_release.240331-1435
BuildLabEx                : 26100.1.amd64fre.ge_release.240331-1435
CompositionEditionID      : Enterprise
CurrentBuild              : 26100
CurrentBuildNumber        : 26100
CurrentMajorVersionNumber : 10
CurrentMinorVersionNumber : 0
CurrentType               : Multiprocessor Free
CurrentVersion            : 6.3
DisplayVersion            : 24H2
EditionID                 : Professional
InstallationType          : Client
InstallDate               : 1719779588
LCUVer                    : 10.0.26100.2152
ProductName               : Windows 10 Pro
'@
$YAML | ConvertFrom-YAML | Format-List
```

...the output is as undermentioned:

```YAML
Name  : InstallDate
Value : 1719779588

Name  : BuildLab
Value : 26100.ge_release.240331-1435

Name  : EditionID
Value : Professional

Name  : CompositionEditionID
Value : Enterprise

Name  : CurrentType
Value : Multiprocessor Free

Name  : ProductName
Value : Windows 10 Pro

Name  : LCUVer
Value : 10.0.26100.2152

Name  : BuildBranch
Value : ge_release

Name  : CurrentMajorVersionNumber
Value : 10

Name  : CurrentBuildNumber
Value : 26100

Name  : CurrentVersion
Value : 6.3

Name  : CurrentMinorVersionNumber
Value : 0

Name  : DisplayVersion
Value : 24H2

Name  : BuildLabEx
Value : 26100.1.amd64fre.ge_release.240331-1435

Name  : SystemRoot
Value : C:\WINDOWS

Name  : InstallationType
Value : Client

Name  : CurrentBuild
Value : 26100
```

The differences are most visible if I utilize the undermentioned command:

```PS1
$YAML | ConvertFrom-YAML | Format-Table -AutoSize
```

...where the output is actually more akin to that of `Format-List`, due to the encapsulation of these values:

```Markdown
Name                      Value
----                      -----
InstallDate               1719779588
BuildLab                  26100.ge_release.240331-1435
EditionID                 Professional
CompositionEditionID      Enterprise
CurrentType               Multiprocessor Free
ProductName               Windows 10 Pro
LCUVer                    10.0.26100.2152
BuildBranch               ge_release
CurrentMajorVersionNumber 10
CurrentBuildNumber        26100
CurrentVersion            6.3
CurrentMinorVersionNumber 0
DisplayVersion            24H2
BuildLabEx                26100.1.amd64fre.ge_release.240331-1435
SystemRoot                C:\WINDOWS
InstallationType          Client
CurrentBuild              26100
```

#### **Questions**

1. Why does it encapsulate the values with standard names? This is a very different format to its input. I'm rather surprised that it's so transformative by default.
1. Irrespective, can it be disabled? If not, might I know why?

**Comment by gabriel-samfira** [comment]
That is a particularity of Format-List when you give it a Hash Table. It's not encapsulated in anything. A hash table is a key-value pair data structure. As such, Format-List will format a hash table in 2 fields: Name and Value.

**Reply by beedell-roke** [reply]
> That is a particularity of `Format-List` when you give it a Hash Table.

@gabriel-samfira, that doesn't make much sense to me, considering that the difference is also evident when using `Format-Table`, as aforestated.

As an example, consider how when it's exported to JSON and reimported to a PSObject, the keys and values are not subordinate to a `Name` and `Value` key respectively. Undermentioned, I attempt to demonstrate this using a more concise example, and the default `ConvertTo-JSON` command:

1.	```PS1
	#!/usr/bin/env -S pwsh
	Install-Module -Name 'MonitorConfig' -RequiredVersion 1.0.3
	$DeviceName = '\\.\DISPLAY1'
	```

1.	*	1.	```PS1
			Get-Monitor -DeviceName "$DeviceName" | ConvertTo-YAML
			```

		1.	```YAML
			LogicalDisplay:
			IsPrimary: true
			DeviceName: '\\.\DISPLAY1'
			Bounds:
			  left: 0
			  top: 0
			  right: 2560
			  bottom: 1440
			WorkingArea:
			  left: 0
			  top: 0
			  right: 2560
			  bottom: 1392
			FriendlyName: Generic PnP Monitor
			InstanceName: DISPLAY\BNQ7F87\7&1a33d6cf&1&UID256
			```

	*	1.	```PS1
			Get-Monitor -DeviceName "$DeviceName" | ConvertTo-JSON
			```

		1.	<blockquote>
		
			```JSON
			{
			"LogicalDisplay": {
				"IsPrimary": true,
				"DeviceName": "\\\\.\\DISPLAY1",
				"Bounds": {
				"left": 0,
				"top": 0,
				"right": 2560,
				"bottom": 1440
				},
				"WorkingArea": {
				"left": 0,
				"top": 0,
				"right": 2560,
				"bottom": 1392
				}
			},
			"FriendlyName": "Generic PnP Monitor",
			"InstanceName": "DISPLAY\\BNQ7F87\\7&1a33d6cf&1&UID256"
			}
			```

			</blockquote>

1.	```PS1
	$JSON = (Get-Monitor -DeviceName "$DeviceName" | ConvertTo-JSON)
	$YAML = (Get-Monitor -DeviceName "$DeviceName" | ConvertTo-YAML)
	```

1.	*	1.	```PS1
			$JSON | ConvertFrom-JSON | Format-List
			```

		1.	<blockquote>
		
			```YAML
			LogicalDisplay : @{IsPrimary=True; DeviceName=\\.\DISPLAY1; Bounds=; WorkingArea=}
			FriendlyName   : Generic PnP Monitor
			InstanceName   : DISPLAY\BNQ7F87\7&1a33d6cf&1&UID256
			```

			</blockquote>

	*	1.	```PS1
			$YAML | ConvertFrom-YAML | Format-List
			```

		1.	<blockquote>
		
			```YAML
			Name  : LogicalDisplay
			Value : {[DeviceName, \\.\DISPLAY1], [Bounds, System.Collections.Hashtable], [IsPrimary, True], [WorkingArea, System.Collections.Hashtable]}

			Name  : InstanceName
			Value : DISPLAY\BNQ7F87\7&1a33d6cf&1&UID256

			Name  : FriendlyName
			Value : Generic PnP Monitor
			```

			</blockquote>
