### DISCUSSION TITLE
Encountered a problem during the conversion of Azure DevOps YAML to a PowerShell object.

### DISCUSSION THREAD

**Discussion by naitikkumar** [cloudbase/powershell-yaml#184] [Show and tell]
Source Yaml:
```yaml
---
  pool:
    vmImage: ubuntu-latest
  parameters:
    - name:  release-version
      default: ''
      values: 
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
```
```powershell
#version of powershell-yaml 0.4.12
#Above yaml is saved at location mentioned in variable $file 
#script:
# Read the YAML file
$file = "c:\temp\pipeline.yaml"
$output = "c:\temp\outfile.yaml"
$newcont1 = Get-Content -Path $file -Raw | convertfrom-yaml

# Update the parameters
foreach ($param in $newcont1.parameters ) {
    if ($param.name -like "release-version") {
         $param.values = $blob 
         $param.default = $firstobject 
    }
}

$Yaml = $newcont1 | ConvertTo-Yaml

$Yaml | Set-Content -Path $output 
```

Output:
```yaml
---
pool:
  vmImage: ubuntu-latest
parameters:
- values:
  -  apps-conf-feature-3097.zip
  - apps-conf-feature3096.zip
  default: apps-conf-feature3096.zip
  name:  release-version
steps:
- script: echo Hello, world!
  displayName: Run a one-line script
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: Run a multi-line script
```
Observation: Name should be child but values is child
