### ISSUE TITLE
Yaml output is not respected when exporting Powershell nested classes.

### ISSUE THREAD

**Issue by Stephanevg** [cloudbase/powershell-yaml#118]
Hi, I do have the following issue.

```powershell
Class WoopCol {
  [woop[]]$Woops

  add([woop]$woop){
    $this.Woops += $woop
  }
}
Class woop {
  [String]$Name = "woop"
  [String]$Status = "running"
}

$col = [woopCol]::New()
$woop = [woop]::New()
$wap = [woop]::New()
$wap.Name = "wap"

$col.add($woop)
$col.add($wap)

$col | ConvertTo-Yaml

```

the result I get is the following:

```yaml
Woops:
  - Name: woop
    Status: running
  - Name: wap
    Status: running
```

What I am actually expecting is:

```yaml
woop: running
wap: running
```

Would this be the same root issue as #106  ?
