### ISSUE TITLE
indentation for arrays back import of arrays / dictionaries

### ISSUE THREAD

**Issue by cap-flie** [cloudbase/powershell-yaml#192]
when using the following script to generate the yaml file the list is not properly indented. 
Is this intended?

```powershell
  $config = [PSCustomObject]@{
    some_value = $some_value
    some_values       = @(
      [PSCustomObject]@{
        email = "some_email1"
        role  = "some_role"
      },
      [PSCustomObject]@{
        email = "some_email2"
        role  = "some_role"
      },
      [PSCustomObject]@{
        email = "some_email3"
        role  = "some_role"
      }
    )
  }
  
  $filename = $("some_name" + ".yaml")
  New-Item -ItemType File -Path $filename -Force
  $config | ConvertTo-Yaml | Set-Content $filename
```

is:

```yaml
some_value:
some_values:
- email: some_email1
  role: some_role
- email: some_email2
  role: some_role
- email: some_email3
  role: some_role
```

should be

```yaml
some_value:
some_values:
  - email: some_email1
    role: some_role
  - email: some_email2
    role: some_role
  - email: some_email3
    role: some_role
```

also when importing the output back its formated quite differently:

```powershell
$config

some_value some_values
---------- -----------
           {@{email=some_email1; role=some_role}, @{email=some_email2; role=some_role}, @{email=some_email3; role=some_role}}

Get-Content some_name.yaml | convertfrom-yaml

Name                           Value
----                           -----
some_values                    {System.Collections.Hashtable, System.Collections.Hashtable, System.Collections.Hashtable}
some_value
```
