### ISSUE TITLE
ConvertTo-Yaml is converting `|` blocks into `>`

### ISSUE THREAD

**Issue by Ash258** [cloudbase/powershell-yaml#40]
When doing something like `Get-Content example.yaml -Raw -Encoding UTF8 | ConvertFrom-Yaml -Ordered | ConvertTo-Yaml` you will see that `|` blocks are converted into `>` with blank spaces

Could I somehow force / set options to keep `|` type?

Input file:

```yaml
version: 2.4.37
description: Apache web server.
homepage: https://www.apachelounge.com
persist:
  - htdocs
  - conf
bin:
  - bin\ab.exe
pre_install: |
  Write-Host 'Installing'
  Write-Host 'Installing'
post_install: |
  # set directory in httpd.conf
  $conf = "$dir\conf\httpd.conf"
  $root = (scoop which httpd | Split-Path -Resolve -Parent | Split-Path -Parent) -replace '\\', '/'
  (Get-Content $conf) -replace 'c:/Apache\d+', "$root" | Set-Content $conf
checkver:
  url: https://www.apachelounge.com/download/
  regex: Apache ([\d\.]+) Win64
```

Output:

```yaml
....
pre_install: >
  Write-Host 'Installing'

  Write-Host 'Installing'
post_install: >
  # set directory in httpd.conf

  $conf = "$dir\conf\httpd.conf"

  $root = (scoop which httpd | Split-Path -Resolve -Parent | Split-Path -Parent) -replace '\\', '/'

  (Get-Content $conf) -replace 'c:/Apache\d+', "$root" | Set-Content $conf
```
