### ISSUE TITLE
Block scalars are not parsed as array

### ISSUE THREAD

**Issue by Ash258** [cloudbase/powershell-yaml#48]
Scalar blocks should be parsed as array. 

```yml
# test yaml for desription
installer_block: |
  Get-Content 'Alfa.txt'
  Write-Host 'Test' -f Yellow
installer_arr:
  - Get-Content 'Alfa.txt'
  - Write-Host 'Test' -f Yellow
```

```powershell
$yaml = Get-Content -Raw .\test.yml | ConvertFrom-Yaml
$yaml.installer_arr.Count
2
$yaml.installer_block.Count
1 # Should be 2

**Comment by gabriel-samfira** [comment]
Hi @Ash258 

A scalar block is essentially a multi-line string. See: https://yaml-multiline.info/

Python parses it the same way:

```python
>>> import yaml
>>> a = yaml.safe_load(open("test.yaml"))
>>> a
{'installer_block': "Get-Content 'Alfa.txt'\nWrite-Host 'Test' -f Yellow\n", 'installer_arr': ["Get-Content 'Alfa.txt'", "Write-Host 'Test' -f Yellow"]}
>>> a["installer_block"]
"Get-Content 'Alfa.txt'\nWrite-Host 'Test' -f Yellow\n"
>>> type(a["installer_block"])
<class 'str'>
```

You can store commands in arrays if you wish. There is no reason to have 2 distinct types act in the same way.

You can emulate that behaviour if you wish by simply splitting the block:

```powershell
$yaml = Get-Content -Raw .\test.yml | ConvertFrom-Yaml
$yaml.installer_block.Split("`n")
```
Which will even ignore ```\n``` if it's specified in the yaml, literally:

```yaml
# test yaml for desription
installer_block: |
  Get-Content 'Alfa.txt\nTest2'
  Write-Host 'Test' -f Yellow
installer_arr:
  - Get-Content 'Alfa.txt'
  - Write-Host 'Test' -f Yellow
```

```powershell
PS /tmp> $yaml.installer_block.Split("`n")
Get-Content 'Alfa.txt\nTest2'
Write-Host 'Test' -f Yellow
```
