### ISSUE TITLE
ConvertFrom-Yaml  fails when reading yaml containing multiple documents

### ISSUE THREAD

**Issue by jaijitendra** [cloudbase/powershell-yaml#49]
when I execute below
 `ConvertFrom-Yaml -Yaml $(Get-Content "E:\file.yaml") -AllDocuments`

I get below error:
```
ConvertFrom-Yaml : Cannot process argument transformation on parameter 'Yaml'. Cannot convert value to type System.String.
At line:1 char:29
+ ... tFrom-Yaml -Yaml $(Get-Content "E:\file.yaml") -AllDoc ...
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertFrom-Yaml], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,ConvertFrom-Yaml

```
Here is my yaml file.
```
---
# Source: A/templates/A-poddisruption.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: A
  namespace: A
  labels:
    app: A
    tier: A
spec:
  maxUnavailable: 20%
  selector:
    matchLabels: 
      app: A
---
# Source: A/templates/B-loadbalancer.yaml
apiVersion: v1
kind: Service
metadata:
  name: B
  namespace:A
  labels:
    app: A
    tier: A
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: A
    tier: A
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443``
```
