### ISSUE TITLE
Different behavior as ConvertFrom-Json with Get-Content

### ISSUE THREAD

**Issue by timia2109** [cloudbase/powershell-yaml#51]
When I run the command `Get-Content test.json | ConvertFrom-Json | ConvertTo-Yaml`  I got the representing Yaml which works.

When I run the command `Get-Content -Raw test.yaml | ConvertFrom-Yaml | ConvertTo-Yaml` everything works as expected.

When I run the command `Get-Content test.yaml | ConvertFrom-Yaml | ConvertTo-Yaml` I got an array with each property as object. 

### Example:
test.yaml
```yaml
id: m1
isRoot: true
delay: 0
text: Test
```

Output: 
```yaml
- id: m1
- isRoot: true
- delay: 0
- text: Test
```

I think this is confusing because I expect that all converters should work the same way
I know that Get-Content parse each line, but this should recognized automatically like on ConvertFrom-Json.

Tested with Powershell 5.1 on Windows and Powershell Core 6.2 on Windows and MacOS
