### ISSUE TITLE
Multiline String Support

### ISSUE THREAD

**Issue by ephos** [cloudbase/powershell-yaml#58]
Hello, I saw another issue open and then closed by the person that opened it regarding this with no other comments.  

**Current state:**

```yaml
something:
  name: test
  key:
  - '-----BEGIN PGP MESSAGE-----'
  - 'Version: GnuPG v2.0.22 (GNU/Linux)'
  - 'blah'
  - 'blah'
  - 'blah'
  - '-----END PGP MESSAGE-----'
```

**Desired state:**

```yaml
something:
  name: test
  key: |
    -----BEGIN PGP MESSAGE-----
    Version: GnuPG v2.0.22 (GNU/Linux)
    blah
    blah
    blah
    -----END PGP MESSAGE-----
```

Apologies if it is something I am doing, I tried various options but couldn't seem to get it to handle the multiline string.
