### ISSUE TITLE
Adding in newline blocks when converting powershell object to yaml

### ISSUE THREAD

**Issue by shiftychris** [cloudbase/powershell-yaml#80]
Hi there,

Cant seem to find the documentation for this answer but hope someone will point me in the right direction. I am trying to add in new line within the yaml. I am using the code below: 

```
$yamlObject = [PSCustomObject]@{ "objects" =  @{"array"=  @(
				[PSCustomObject]@{
                    "" = \n;
					"objectName" = "";
					"objectAlias" = "";
					"objectType" = "";
				},
				[PSCustomObject]@{
					"objectName" = "";
					"objectAlias" = "";
					"objectType" = "";
				}
			)}}

ConvertTo-Yaml $yamlObject
```

The output I am trying for is:

```    
objects:  |
      array:
        - |
          objectName: a
          objectAlias: a
          objectType: a
        - |
          objectName: a
          objectAlias: a
          objectType: a
```

If I ConvertFrom-Yaml and then ConvertTo-Yaml it keep the correct yaml but I am unable to define that as a powershell object. Recommendations appreciated.
