### ISSUE TITLE
Unable to deserialize (parse) multiple document YAML file

### ISSUE THREAD

**Issue by martincrothers** [cloudbase/powershell-yaml#83]
When trying to deserialize a YAML file with multiple documents, only the first document is deserialized.
I'm using version 0.4.2 of this module, and have tested this in both PS5 and PS7.2.4

Image of the issue:
![powershell-yaml_multiDoc](https://user-images.githubusercontent.com/52473634/171663193-b16afa79-d187-45b9-8479-f9b039e00df4.png)

Document I tried (a short test file):
```
---
# First document
Doc1:
  VehicleTypes:
    - Truck
    - Muscle Car
    - Mini Van
  FuelTypes:
    - Gasoline
    - Diesel

...
---
# Second document
Doc2:
  Fruits:
    - Apple
    - Banana
    - Cherry
  Vegetables:
    - Celery
    - Spinach
    - Broccoli

...
```

Am I doing something wrong, or is there an issue/the module not being compatible with multiple document files?
