### ISSUE TITLE
YAML file creation from scratch

### ISSUE THREAD

**Issue by nkrishnakishor** [cloudbase/powershell-yaml#91]
Hi Team,

I'm creating the below `yaml` file with below format from scratch which has only the `value1:` content rest are being added to it.

```
value1:
value2:
  - key:
    - subkey1
    - subkey2
  - key:
    - another
  - someOtherKey:
    - someOtherSubKey
```

Below is the procedure I tried 
```
PS C:\Users\user1> $file.Add('value2',@())
PS C:\Users\user1> $file

Name                           Value
----                           -----
value1
value2                      {}


PS C:\Users\user1> $file.value2[0].add('key','subkey1')
You cannot call a method on a null-valued expression.
At line:1 char:1
+ $file.value2[0].add('key','subkey1')
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

can anyone help me where I'm going wrong
