### ISSUE TITLE
Supporting a different schema 

### ISSUE THREAD

**Issue by ex0nuss** [cloudbase/powershell-yaml#96]
Hi,
just discovered this module and it looks fantastic!

I would like to automatically edit a YAML from an application called "Tuneup PRIME" I use. Unfortunately the schema is somewhat weird and I the formatting of the yaml is fixed, here is an example snippet of the YAML:
```
smartPlaylists: 
    - name: Highlight
      rules:
        or:
          - [comment, contains, Highlight]
          - [comment, contains, Main]
    - name: Intros
      rules:
        or:
          - [comment, contains, Intros]
```
After running it through PowerShell it looks like this:
```
Import-Module powershell-yaml
$yaml = Get-Content -Path ".\example.yaml"
$obj = ConvertFrom-Yaml $($yaml | Out-String)
$obj
$obj.smartPlaylists
```
>![image](https://user-images.githubusercontent.com/61937793/217322202-f238d790-fedc-41f0-9c9c-09bf9200c387.png)

This is the schema of the YAML: https://raw.githubusercontent.com/rshea0/tuneup-prime/master/src/app/engine/library-config/tuneup.schema.json
Is there any way to fix this?

Thank you in advance, Max
